version: '3.4'

name: 'react-pokedex'

services:
  react:
    network_mode: bridge
    stdin_open: true
    user: node
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    command: yarn serve
    volumes:
      - ./:/srv/app

  cypress:
    network_mode: bridge
    depends_on:
      - react
    image: "cypress/included:12.5.1"
    working_dir: /srv/app/test/Framework/Integration
    command: "--config baseUrl=http://172.17.0.1:3000/ --spec cypress/e2e/TasksViewIntegration.cy.ts"
    volumes:
      - ./:/srv/app
